# CUDA_VISIBLE_DEVICES=1 llamafactory-cli train examples/train_lora/llava1_5_lora_sft.yaml
### model
model_name_or_path: /root/huggingface/llava-hf/llava-1.5-7b-hf
trust_remote_code: true

### met
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: mllm_demo
template: llava
cutoff_len: 4096
max_samples: 8000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llava1_5-7b/lora/sft_15_t+c+sc
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
mask_history: True

# ### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
